export const ACTIONS = {
  SET_MODAL: "SET_MODAL",
  SET_INPUT: "SET_INPUT",
  SET_DATES_ARRAY: "SET_DATES_ARRAY",

  SET_LOCATIONS_DATA: "SET_LOCATIONS_DATA",
  SET_BRANDS_DATA: "SET_BRANDS_DATA",
  SET_MODELS_DATA: "SET_MODELS_DATA",
  SET_TRIMS_DATA: "SET_TRIMS_DATA",

  SET_TRANSMISSIONS_DATA: "SET_TRANSMISSIONS_DATA",
  SET_FUELTYPES_DATA: "SET_FUELTYPES_DATA",
  SET_COLORS_DATA: "SET_COLORS_DATA",
};
